/*
 * 86Box    A hypervisor and IBM PC system emulator that specializes in
 *          running old operating systems and software designed for IBM
 *          PC systems and compatibles from 1981 through fairly recent
 *          system designs based on the PCI bus.
 *
 *          This file is part of the 86Box distribution.
 *
 *          VideoCommon shader module -- SPIR-V loading and
 *          VkShaderModule creation.
 *
 *          SPIR-V bytecode is compiled offline by glslc and embedded as
 *          C header arrays (voodoo_uber_vert.h and _frag.h).
 *          No runtime shader compilation.
 *
 * Authors: skiretic
 *
 *          Copyright 2026 skiretic.
 */
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>

#include "vc_internal.h"

#define HAVE_STDARG_H
#include <86box/86box.h>

#include "vc_shader.h"

/* Embedded SPIR-V bytecode -- generated by CMake from glslc.
   Each header defines a static const uint32_t array and a _size constant. */
#include "voodoo_uber_vert.h"
#include "voodoo_uber_frag.h"

/* -------------------------------------------------------------------------- */
/*  Internal helpers                                                           */
/* -------------------------------------------------------------------------- */

static VkShaderModule
vc_create_shader_module(VkDevice device, const uint32_t *code, size_t size)
{
    VkShaderModuleCreateInfo ci;
    memset(&ci, 0, sizeof(ci));
    ci.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    ci.codeSize = size;
    ci.pCode    = code;

    VkShaderModule module = VK_NULL_HANDLE;
    VkResult       result = vkCreateShaderModule(device, &ci, NULL, &module);
    if (result != VK_SUCCESS) {
        VC_LOG("VideoCommon: vkCreateShaderModule failed (%d)\n", result);
        return VK_NULL_HANDLE;
    }

    return module;
}

/* -------------------------------------------------------------------------- */
/*  Public API                                                                 */
/* -------------------------------------------------------------------------- */

int
vc_shaders_create(vc_ctx_t *ctx, vc_shaders_t *shaders)
{
    memset(shaders, 0, sizeof(vc_shaders_t));

    shaders->vert = vc_create_shader_module(ctx->device,
                                            voodoo_uber_vert_spv,
                                            voodoo_uber_vert_spv_size);
    if (shaders->vert == VK_NULL_HANDLE) {
        VC_LOG("VideoCommon: failed to create vertex shader module\n");
        return -1;
    }

    shaders->frag = vc_create_shader_module(ctx->device,
                                            voodoo_uber_frag_spv,
                                            voodoo_uber_frag_spv_size);
    if (shaders->frag == VK_NULL_HANDLE) {
        VC_LOG("VideoCommon: failed to create fragment shader module\n");
        vkDestroyShaderModule(ctx->device, shaders->vert, NULL);
        shaders->vert = VK_NULL_HANDLE;
        return -1;
    }

    VC_LOG("VideoCommon: shader modules created (vert + frag)\n");
    return 0;
}

void
vc_shaders_destroy(vc_ctx_t *ctx, vc_shaders_t *shaders)
{
    if (!shaders)
        return;

    if (shaders->frag != VK_NULL_HANDLE) {
        vkDestroyShaderModule(ctx->device, shaders->frag, NULL);
        shaders->frag = VK_NULL_HANDLE;
    }

    if (shaders->vert != VK_NULL_HANDLE) {
        vkDestroyShaderModule(ctx->device, shaders->vert, NULL);
        shaders->vert = VK_NULL_HANDLE;
    }
}
